### ISSUE TITLE
Adding new features of blocking days

### ISSUE THREAD

**Issue by hkmsadek** [ajhaupt7/vue-custom-datepicker#1]
It's actually not an issue. First of all thank you for such a nice awesome project. 

I an wondering if it's possible to add options for restricting to only those dates we want along with start and end limit. It a good idea with start and end date but if we could add a restriction of date would be great. 

For example, let's say we want to show 10 dates then only show those dates and rest is blocked. 

Any idea how to achieve it or what files to edit would be great. Also if you can update it would be nice. 

Thank you

**Comment by ajhaupt7** [comment]
@hkmsadek feel free to open a PR with changes. This wouldn't be much work to add -- you could add a new prop (something like `excludedDates`) that takes an array of dates, then factor that into the `isWithinActiveRange` function. Just add an additional check that returns false if the date is part of the `excludedDates` array. All logic lives in CustomDatepicker.vue
